# Generated by Django 4.1.5 on 2023-01-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Places',
        ),
    ]
